{
    'name': 'Asset Financing Management',
    'version': '1.0.0',
    'category': 'Accounting/Leasing',
    'summary': 'Manage Asset Financing, HP, and Leasing Contracts',
    'author': 'Mofisoft PTE. LTD.',
    'depends': ['base', 'account', 'sale', 'purchase', 'fleet'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/cron.xml',
        'data/finance_term_data.xml',
        'data/account_chart_data.xml',
        'views/asset_views.xml',
        'views/res_partner_views.xml',
        'views/product_views.xml',
        'views/penalty_views.xml',
        'views/contract_views.xml',
        'wizard/settlement_views.xml',
        'wizard/disbursement_wizard_views.xml',
        'views/account_payment_views.xml',
        'views/menu_views.xml',
        'reports/finance_reports.xml',
        'reports/finance_contract_template.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}