{
    'name': 'Vehicle Financing Management',
    'version': '1.0.0',
    'category': 'Accounting/Leasing',
    'summary': 'Manage Vehicle Assets, HP, and Leasing Contracts',
    'author': 'Mofisoft PTE. LTD.',
    'depends': ['base', 'account', 'sale', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/cron.xml',
        'views/vehicle_views.xml',
        'views/product_views.xml',
        'views/penalty_views.xml',
        'views/contract_views.xml',
        'wizard/settlement_views.xml',
        'views/account_payment_views.xml',
        'views/menu_views.xml',
        'reports/leasing_reports.xml',
        'reports/leasing_contract_template.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}